cmd/rollout/app/options/options.go, cmd/rollout/app/rollout.go, cmd/rollout/main.go
=> fix: add ClusterManagementGVR when to use federated controller runtime

cmd/rollout/app/rollout.go, cmd/rollout/main.go, go.mod, go.sum, pkg/controllers/rolloutrun/rolloutrun_controller.go, pkg/utils/cli/flag.go
=> fix: bump up kube-utils to correct discovery result in multicluster

pkg/utils/cli/flag.go
=> fix: retrieve solely the kubeconfig flag from flag.CommandLine.

go.sum, pkg/webhook/pod/mutating/pod_create_update_handler.go
=> fix: get rolloutID instead of rolloutRun in progressingInfo

pkg/backend/registry/registry.go, pkg/backend/service/store.go, pkg/controllers/backendrouting/backendrouting_controller.go, pkg/controllers/backendrouting/backendrouting_controller_suite_test.go, pkg/controllers/backendrouting/backendrouting_controller_test.go, pkg/controllers/backendrouting/initializer.go, pkg/controllers/init_backendrouting.go, pkg/controllers/traffictopology/adapter.go, pkg/controllers/traffictopology/event_handler.go, pkg/controllers/traffictopology/traffictopology_controller.go, pkg/controllers/traffictopology/traffictopology_controller_suite_test.go, pkg/controllers/traffictopology/traffictopology_controller_test.go, pkg/controllers/traffictopology/types.go, pkg/route/ingress/route.go, pkg/route/ingress/store.go, pkg/route/registry/registry.go, pkg/utils/slice_test.go
=> fix cilint

apis/rollout/v1alpha1/traffic_route_types.go, config/crd/bases/rollout.kusionstack.io_traffictopologies.yaml, pkg/backend/service/backend.go, pkg/controllers/traffictopology/adapter.go
=> fix service gvk

pkg/backend/service/backend.go, pkg/controllers/backendrouting/backendrouting_controller.go, pkg/controllers/backendrouting/backendrouting_controller_suite_test.go, pkg/controllers/backendrouting/backendrouting_controller_test.go, pkg/route/ingress/route.go, pkg/route/registry/registry.go
re #47 
```release-note
None
```
=> backendrouting controller ut

pkg/controllers/backendrouting/backendrouting_controller.go, pkg/controllers/backendrouting/backendrouting_controller_suite_test.go, pkg/controllers/backendrouting/backendrouting_controller_test.go
=> fix missing routeStatues and npe if canary backend not exist

apis/rollout/v1alpha1/traffic_route_types.go, pkg/controllers/backendrouting/backendrouting_controller.go, pkg/controllers/backendrouting/backendrouting_controller_test.go, pkg/route/ingress/route.go, pkg/route/interface.go
=> fix canary route's backend not changed and add few unit tests

pkg/controllers/backendrouting/backendrouting_controller.go, pkg/controllers/backendrouting/backendrouting_controller_test.go
=> add ut for ending canary in backendrouting controller

pkg/controllers/traffictopology/adapter.go, pkg/controllers/traffictopology/traffictopology_controller_test.go
=> feat: support deleting backendrouting when traffictopology is terminating

pkg/controllers/backendrouting/backendrouting_controller_test.go, pkg/route/ingress/const.go, pkg/route/ingress/route.go
=> fix missing canary ingress's canary:true anno

pkg/controllers/rolloutrun/control/control.go, pkg/workload/accessor.go, pkg/workload/collaset/accessor.go, pkg/workload/collaset/release.go, pkg/workload/statefulset/accessor.go, pkg/workload/statefulset/release.go
=> fix(canary): apply changes to canary object in creation

pkg/controllers/rolloutrun/control/control.go
This commit corrects the release cleanup logic to recycle canary objects
after the canary release phase is complete, rather than erroneously
removing stable objects. The updated logic helps maintain service stability
and ensures a proper transition from canary to stable environment.
```release-note
None
```
=> fix(canary): ensure canary objects are recycled post canary release instead of deleting stable one

go.mod, go.sum, hack/local-dev.sh, pkg/utils/cert/cert.go, pkg/utils/cert/cert_test.go, pkg/utils/cert/error.go, pkg/utils/cert/error_test.go, pkg/utils/cert/fs.go, pkg/utils/cert/secret.go, pkg/webhook/controller/syncer.go, pkg/webhook/env_config.go, pkg/webhook/webhook.go
=> feat: add webhook cert sync controller

apis/rollout/v1alpha1/rollout_types.go, apis/rollout/v1alpha1/rolloutrun_types.go, apis/rollout/v1alpha1/traffic_route_types.go, config/crd/bases/rollout.kusionstack.io_backendroutings.yaml, config/crd/bases/rollout.kusionstack.io_rolloutruns.yaml, config/crd/bases/rollout.kusionstack.io_rollouts.yaml, config/crd/bases/rollout.kusionstack.io_traffictopologies.yaml
=> chore(crd): add more additionalPrinterColumns

pkg/utils/cert/cert_test.go
=> test(cert): add ut for GenerateSelfSignedCerts

pkg/utils/cert/fs.go, pkg/utils/cert/secret.go, pkg/webhook/controller/syncer.go
=> fix(cert): return corret secret operation error

pkg/utils/cert/cert.go, pkg/utils/cert/fs.go, pkg/utils/cert/secret.go, pkg/webhook/controller/syncer.go
=> fix(secrets):update secret provider to accept context for multi-cluster support

pkg/controllers/rolloutrun/control/control.go
=> fix: avoid dropping other finalizers in canary workload

apis/rollout/v1alpha1/rollout_types.go, apis/rollout/v1alpha1/validation/rolloutrun.go, apis/rollout/v1alpha1/validation/rolloutrun_test.go, apis/rollout/v1alpha1/validation/rolloutstrategy.go, apis/rollout/v1alpha1/validation/rolloutstrategy_test.go, config/crd/bases/rollout.kusionstack.io_rollouts.yaml, hack/local-dev.sh, pkg/controllers/rollout/rollout_controller.go, pkg/controllers/rollout/utils.go, pkg/webhook/rollout/validating/rollout.go
Note: 
1. With pull requests:
- Open your pull request against "main"
- Your pull request should have no more than two commits, if not you should squash them.
- It should pass all tests in the available continuous integration systems such as GitHub Actions.
- You should add/modify tests to cover your proposed code changes.
- If your pull request contains a new feature, please document it on the README.
2. Please create an issue first to describe the problem.
We recommend that link the issue with the PR in the following question.
For more info, check https://kusionstack.io/docs/governance/contribute/
-->
fix #84 
```release-note
None
```
=> fix(validation): validate the existence of dependent resources during rollout controller runtime, rather than in webhook

pkg/controllers/podcanarylabel/event_handler.go, pkg/controllers/podcanarylabel/podcanarylabel.go, pkg/workload/collaset/accessor.go, pkg/workload/interface.go, pkg/workload/statefulset/accessor.go
=> feat: Add a client.Reader to create a PodControl instance

pkg/webhook/pod/mutating/pod_create_update_handler.go
=> refactor: delete noise logs in pod mutating webhook

pkg/controllers/rollout/rollout_controller.go
=> fix(rollout): export FailedCreated error message in Trigger condition, not Progressing

go.mod, go.sum, pkg/controllers/podcanarylabel/event_handler.go, pkg/controllers/podcanarylabel/podcanarylabel.go, pkg/controllers/registry/workload_test.go, pkg/controllers/rolloutrun/control/control.go, pkg/controllers/rolloutrun/executor/batch.go, pkg/controllers/rolloutrun/executor/batch_test.go, pkg/controllers/rolloutrun/executor/canary.go, pkg/controllers/rolloutrun/executor/context.go, pkg/controllers/rolloutrun/executor/context_test.go, pkg/controllers/rolloutrun/executor/default_test.go, pkg/workload/collaset/pod_control.go, pkg/workload/collaset/release.go, pkg/workload/collaset/release_test.go, pkg/workload/interface.go, pkg/workload/poddecoration/accessor.go, pkg/workload/poddecoration/release.go, pkg/workload/poddecoration/release_test.go, pkg/workload/statefulset/accessor.go, pkg/workload/statefulset/pod_control.go, pkg/workload/statefulset/release.go, pkg/workload/statefulset/release_test.go
=> feat: add workload for PodDecoration

pkg/controllers/podcanarylabel/podcanarylabel.go, pkg/workload/collaset/pod_control.go, pkg/workload/interface.go, pkg/workload/statefulset/pod_control.go
=> fix(workload): require client.Reader for IsUpdatedPod function

pkg/controllers/rolloutrun/control/control.go, pkg/controllers/rolloutrun/executor/batch.go, pkg/controllers/rolloutrun/executor/batch_test.go, pkg/controllers/rolloutrun/executor/default_test.go, pkg/workload/collaset/accessor.go, pkg/workload/collaset/pod_control.go, pkg/workload/collaset/release.go, pkg/workload/collaset/release_test.go, pkg/workload/interface.go, pkg/workload/poddecoration/release.go, pkg/workload/poddecoration/release_test.go, pkg/workload/statefulset/release.go, pkg/workload/statefulset/release_test.go, pkg/workload/util.go, pkg/workload/util_test.go
=> feat: revert collaset partition logic to maintain compatibility with operating v0.5.0

pkg/webhook/pod/mutating/pod_create_update_handler.go, pkg/webhook/rollout/validating/rollout.go
=> chore: fix webhook manifest generator marker

pkg/controllers/backendrouting/backendrouting_controller_suite_test.go, pkg/controllers/traffictopology/traffictopology_controller_suite_test.go, pkg/workload/collaset/release.go, pkg/workload/collaset/release_test.go, pkg/workload/poddecoration/release.go, pkg/workload/poddecoration/release_test.go, pkg/workload/statefulset/release.go, pkg/workload/statefulset/release_test.go
=> fix: do not change workload spec if it already meets the condition

build/rollout/Dockerfile, config/kind/prerequisite/namespace.yaml, config/kind/webhook/outcluster/delete-svc.yaml, config/kind/webhook/outcluster/kustomization.yaml, config/kind/webhook/outcluster/patches/service.yaml, config/kind/webhook/outcluster/patches/webhook.yaml, config/kind/webhook/outcluster/webhook-hosts.env, config/kind/workload/overlays/v2/demo1-v2.yaml, config/kind/workload/overlays/v2/demo2-v2.yaml, config/webhook/kustomization.yaml, config/webhook/manifests.yaml, config/webhook/service.yaml, go.mod, go.sum, hack/lib/kind.sh, hack/local-dev.sh, pkg/controllers/rollout/rollout_controller.go, pkg/controllers/rolloutrun/executor/batch.go, pkg/controllers/rolloutrun/rolloutrun_controller.go, pkg/webhook/init_webhooks.go, pkg/webhook/initializer.go, pkg/webhook/mutating/kuperator/apps_mutating.go, pkg/webhook/mutating/pod/pod_mutating.go, pkg/webhook/mutating/statefulset/sts_mutating.go, pkg/webhook/validating/rollout/rollout_validating.go, pkg/webhook/webhook.go, pkg/workload/collaset/pod_control.go, pkg/workload/statefulset/pod_control.go
=> feat: add mutating wehooks for statefulset, collaset and poddecoration

pkg/controllers/backendrouting/backendrouting_controller_suite_test.go, pkg/controllers/rolloutrun/executor/batch.go, pkg/controllers/rolloutrun/executor/batch_test.go, pkg/controllers/rolloutrun/executor/canary.go, pkg/controllers/rolloutrun/executor/context.go, pkg/controllers/rolloutrun/executor/default.go, pkg/controllers/rolloutrun/executor/default_test.go, pkg/controllers/rolloutrun/executor/do_command.go, pkg/controllers/rolloutrun/executor/do_hook.go, pkg/controllers/rolloutrun/executor/do_hook_test.go, pkg/controllers/traffictopology/traffictopology_controller_suite_test.go, pkg/webhook/generic/generic.go, pkg/webhook/init_webhooks.go, pkg/webhook/initializer.go, pkg/webhook/mutating/kuperator/apps_mutating.go, pkg/webhook/mutating/pod/pod_mutating.go, pkg/webhook/mutating/statefulset/sts_mutating.go, pkg/webhook/validating/rollout/rollout_validating.go, pkg/webhook/webhook.go
=> refactor webhook init function and rolloutRun logger

apis/rollout/v1alpha1/rollout_webhook_types.go, pkg/controllers/rolloutrun/control/control.go, pkg/controllers/rolloutrun/executor/batch.go, pkg/controllers/rolloutrun/executor/canary.go, pkg/controllers/rolloutrun/executor/context.go, pkg/controllers/rolloutrun/executor/default_test.go, pkg/controllers/rolloutrun/rolloutrun_controller.go, pkg/controllers/rolloutrun/webhook/worker_test.go
=> fix: get correct rollout kind from rolloutRun ownerRef

pkg/controllers/rollout/rollout_controller.go, pkg/workload/info.go
=> feat: filter out terminating workload in rollout

pkg/controllers/rolloutrun/executor/default.go
fix #95 
```release-note
None
```
=> fix: error should not block canceling RolloutRun

pkg/controllers/rolloutrun/rolloutrun_controller.go
=> fix: correct canceled RolloutRun phase and condition

build/rollout/Dockerfile, pkg/controllers/rolloutrun/executor/batch.go, pkg/controllers/rolloutrun/executor/batch_test.go
=> fix: avoid changing workload partition if it has already achieved th desired state

apis/rollout/well_known_annotations.go, apis/rollout/well_known_labels.go, pkg/controllers/rollout/rollout_controller.go, pkg/controllers/rollout/utils.go, pkg/controllers/rolloutrun/rolloutrun_controller.go, pkg/features/features.go, pkg/features/rolloutclasspredicate/rolloutclasspredicate.go
=> feat: rollout reconcile filtered by deployment scene

apis/rollout/well_known_annotations.go, pkg/utils/progressinginfos/progressing_info.go, pkg/utils/progressinginfos/progressing_info_test.go, pkg/webhook/mutating/pod/pod_mutating.go
=> fix: extract progressing info

pkg/controllers/registry/workload.go
=> feat: abstract workload get owner

go.mod, go.sum, pkg/webhook/webhook.go
=> fix: panic on writing secret with multicluster client

apis/rollout/v1alpha1/validation/rolloutrun.go, apis/rollout/v1alpha1/validation/rolloutrun_test.go
=> feat(webhook): allow changing replicas in current batch

go.mod, go.sum
=> fix: bump up api

pkg/controllers/rolloutrun/executor/canary.go, pkg/controllers/rolloutrun/rolloutrun_controller.go, pkg/trafficrouting/control/traffic_manager.go
=> fix: get backendrouting from fed
